name: Release new package version

on:
  workflow_dispatch:
    inputs: 
      version-bump:
        type: choice
        description: 'How to bump a version?'
        required: true
        default: 'patch'
        options:
          - major
          - minor
          - patch
          - keep
      pages-only:
        type: boolean
        description: 'Skip release, generate only Github Pages'
        required: true
        default: false
  # push:
  #   branches: [main]
  #   paths:
  #     - '*.scala'        

jobs:
  ReleasePackage:
    runs-on: ubuntu-latest
    steps:
      - id: release
        name: Create and upload new release bundles
        uses: encalmo/create-new-release-action@6f6cf8e666676cb2f9055d4cfe2e63f7c7320b4c
        with:
          tag-prefix: 'version'
          version-bump: ${{ inputs.version-bump || 'patch' }}
          release-flags: '--native'
          github-token:  ${{ secrets.GITHUB_TOKEN }}
          sonatype-token: ${{ secrets.SONATYPE_TOKEN }}
          gpg-secret-key-base64: ${{ secrets.GPG_SECRET_KEY }}
          gpg-secret-key-id: ${{ secrets.GPG_SECRET_KEY_ID }}
          pages-only: '${{ inputs.pages-only }}'
          markdown-paths: 'README.md'
          